// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateUserInput struct {
	Login    string `json:"login"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserPayload struct {
	User  *User                   `json:"user"`
	Token *string                 `json:"token"`
	Error *CreateUserPayloadError `json:"error"`
}

type CreateUserPayloadError struct {
	IsLoginTaken   bool `json:"isLoginTaken"`
	IsLoginInvalid bool `json:"isLoginInvalid"`
}

type LoginUserInput struct {
	Password string `json:"password"`
}

type LoginUserPayload struct {
	User  *User                  `json:"user"`
	Token *string                `json:"token"`
	Error *LoginUserPayloadError `json:"error"`
}

type LoginUserPayloadError struct {
	IsPasswordIncorrect bool `json:"isPasswordIncorrect"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID          string    `json:"id"`
	Login       string    `json:"login"`
	Email       string    `json:"email"`
	CreatedTime time.Time `json:"createdTime"`
	UpdatedTime time.Time `json:"updatedTime"`
}
