// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateUserInput struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type LoginUserInput struct {
	ID string `json:"id"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID          string    `json:"id"`
	Login       string    `json:"login"`
	Email       string    `json:"email"`
	CreatedTime time.Time `json:"createdTime"`
	UpdatedTime time.Time `json:"updatedTime"`
}
